Do not ignore close error
csunibo/filenameslinter pull request #1
Opened 2023-07-17 22:28 UTC by VaiTon

`defer` ignores errors

2023-07-17 23:38 UTC, lucat1 requested changes

2023-07-17 23:38 UTC, lucat1 commented on check.go
> +	err = file.Close()
Basta questa linea qua (con l’uguale e non il :=) e poi un return alla linea dopo.

2023-07-18 00:08 UTC, VaiTon commented on check.go
> +	err = file.Close()
Intendi
```
	err = file.Close()
	return list, err
```
?

2023-07-18 07:10 UTC, lucat1 commented on check.go
> +	err = file.Close()
yes

2023-07-18 07:10 UTC, lucat1 commented on check.go
> +	err = file.Close()
yes

2023-07-18 13:02 UTC, merged